

TOKEN = "604515176:AAEo8pWcb2zfWZGpFhDTagxaotkfIhXJh8Q"

poehavhiy = ["anime", "аниме", "аніме"]

phrases = {}
phrases["истори"] = "https://www.youtube.com/watch?v=XhWvOHAUvL0"
phrases[" вы "] = "https://www.youtube.com/watch?v=Y7N_hXBLWuo"
phrases["завтрак"] = "https://www.youtube.com/watch?v=5hTz0DmBx_Q"
phrases["молчать"] = "https://www.youtube.com/watch?v=ASymneSKNvs"
phrases["знать"] = "https://www.youtube.com/watch?v=dJ-NA86bYQ4"
phrases["шашк"] = "https://www.youtube.com/watch?v=d5JGNnhkMmY"
phrases["рассказывай"] = "https://www.youtube.com/watch?v=cZMz-BoOh30"
phrases["начни"] = "https://www.youtube.com/watch?v=RB7TjieMhUw"
phrases["20"] = "https://www.youtube.com/watch?v=Kq37jErcUrk"
phrases["офицер"] = "https://www.youtube.com/watch?v=5pDy-wCmYAw"
phrases["хлеб"] = "https://www.youtube.com/watch?v=wRw1vh7RMIk"
phrases["мудак"] = "https://www.youtube.com/watch?v=mm5scBcqDBE"
phrases["сумашедший"] = "https://www.youtube.com/watch?v=mm5scBcqDBE"
phrases["вода"] = "https://www.youtube.com/watch?v=vwCBxKMO5RI"
phrases["стру"] = "https://www.youtube.com/watch?v=vwCBxKMO5RI"
phrases["мойся"] = "https://www.youtube.com/watch?v=vwCBxKMO5RI"
phrases["ой"] = "https://youtu.be/lkxs2_l-qdo"
phrases["другое"] = "https://www.youtube.com/watch?v=LC5e75rUzzY"
phrases["хорошое"] = "https://www.youtube.com/watch?v=jwfhZQ4NpcM"
phrases["самолёт"] = "https://www.youtube.com/watch?v=2wjNuC_2yvg"
phrases["истребител"] = "https://www.youtube.com/watch?v=2wjNuC_2yvg"
phrases["корабл"] = "https://www.youtube.com/watch?v=TPsts_sBQH4"
phrases["идиот"] = "https://www.youtube.com/watch?v=up9HaX9ZuZU"
phrases["молчи"] = "https://www.youtube.com/watch?v=rZuwYg5ixj8"
phrases["заткнись"] = "https://www.youtube.com/watch?v=rZuwYg5ixj8"
phrases["хуй"] = "https://www.youtube.com/watch?v=88l3d-2Y78g"
phrases["полковник"] = "https://www.youtube.com/watch?v=4DAOAbsUgUQ"
phrases["конь"] = "https://www.youtube.com/watch?v=4DAOAbsUgUQ"
phrases["салют"] = "https://www.youtube.com/watch?v=4DAOAbsUgUQ"
phrases["сон"] = "https://www.youtube.com/watch?v=Xc_3Tx3jh1M"
phrases["спат"] = "https://www.youtube.com/watch?v=Xc_3Tx3jh1M"
phrases["спал"] = "https://www.youtube.com/watch?v=Xc_3Tx3jh1M"
phrases["врем"] = "https://www.youtube.com/watch?v=mOl2xmpHlmw"
phrases["мне похуй"] = "https://www.youtube.com/watch?v=6MXsLHOi9po"
phrases["мне все равно"] = "https://www.youtube.com/watch?v=6MXsLHOi9po"
phrases["а че"] = "https://www.youtube.com/watch?v=6JOJOe_GNxE"
phrases["а чё"] = "https://www.youtube.com/watch?v=6JOJOe_GNxE"
phrases["груст"] = "https://www.youtube.com/watch?v=YxUANemG0TU"
phrases["вернулся"] = "https://www.youtube.com/watch?v=YxUANemG0TU"
phrases["шишка"] = "https://www.youtube.com/watch?v=ValIvsjEPH4"
phrases["возбуди"] = "https://www.youtube.com/watch?v=ValIvsjEPH4"
phrases["малафлья"] = "https://www.youtube.com/watch?v=E0YTRRylTCk"
phrases["лить"] = "https://www.youtube.com/watch?v=E0YTRRylTCk"
phrases["лилас"] = "https://www.youtube.com/watch?v=E0YTRRylTCk"
phrases["бердянск"] = "https://www.youtube.com/watch?v=Y8pPEJTWfxw"
phrases["азов"] = "https://www.youtube.com/watch?v=YЫ8pPEJTWfxw"
phrases["пытка"] = "https://www.youtube.com/watch?v=XPLYBG8rd6w"
phrases["пытать"] = "https://www.youtube.com/watch?v=XPLYBG8rd6w"
phrases["пока"] = "https://www.youtube.com/watch?v=-4QgaIa7MqE"
phrases["ладно давай"] = "https://www.youtube.com/watch?v=-4QgaIa7MqE"
phrases["люди"] = "https://www.youtube.com/watch?v=ifpzT7136I8"
phrases["за что"] = "https://www.youtube.com/watch?v=SEuIKbcCIrk"
phrases["будьте людьми"] = "https://www.youtube.com/watch?v=y_ZiTsAfS34"
phrases["заткнись"] = "https://www.youtube.com/watch?v=DI1SQkQnW50"
phrases["друг"] = "https://www.youtube.com/watch?v=DI1SQkQnW50"
phrases["мать"] = "https://www.youtube.com/watch?v=jCxBBGDtKls"
phrases["мама"] = "https://www.youtube.com/watch?v=jCxBBGDtKls"
phrases["пидор"] = "https://www.youtube.com/watch?v=aPNshpNtmR4"
phrases["срать"] = "https://www.youtube.com/watch?v=WUvx1bcyjVk"
phrases["деревня"] = "https://www.youtube.com/watch?v=XRMkZU9rjnE"
phrases["село"] = "https://www.youtube.com/watch?v=XRMkZU9rjnE"
phrases["чисти"] = "https://www.youtube.com/watch?v=izYp8oaWohY"
phrases["здоровый"] = "https://www.youtube.com/watch?v=a0hJi-YPfA8"
phrases["пельмень"] = "https://www.youtube.com/watch?v=a0hJi-YPfA8"
phrases["год"] = "https://www.youtube.com/watch?v=kZsHV6ab99s"
phrases["мужик"] = "https://www.youtube.com/watch?v=WV_gsaJaWqY"
phrases["баб"] = "https://www.youtube.com/watch?v=gyFu3SINGl4"
phrases["девушка"] = "https://www.youtube.com/watch?v=gyFu3SINGl4"
phrases["весь в говне"] = "https://www.youtube.com/watch?v=bcy7-hoSzuk"
phrases["не надо"] = "https://www.youtube.com/watch?v=akGyNsKEEy8"
phrases["стукнул"] = "https://www.youtube.com/watch?v=F_oveDMPZ1s"
phrases["крепко"] = "https://www.youtube.com/watch?v=F_oveDMPZ1s"
phrases["работ"] = "https://www.youtube.com/watch?v=NkYU-a-1eOs"
phrases["тапок"] = "https://www.youtube.com/watch?v=rW-oIuwVJ0w"
phrases["курлык"] = "https://www.youtube.com/watch?v=idJKsVao0Kk"
phrases["цапля"] = "https://www.youtube.com/watch?v=idJKsVao0Kk"
phrases["смотри"] = "https://www.youtube.com/watch?v=DbXhXbk2vYA"
phrases["здесь"] = "https://www.youtube.com/watch?v=88I7f_qEvo8"
phrases["орать"] = "https://www.youtube.com/watch?v=UsEg9o1dGS0"
phrases["крик"] = "https://www.youtube.com/watch?v=UsEg9o1dGS0"
phrases["браток"] = "https://www.youtube.com/watch?v=bNoVzRi1V2o"
phrases["класс"] = "https://www.youtube.com/watch?v=ZwMFyqAho-A"
phrases["стоять"] = "https://www.youtube.com/watch?v=By44i1yCkKU"
phrases["стоит"] = "https://www.youtube.com/watch?v=By44i1yCkKU"
phrases["ити"] = "https://www.youtube.com/watch?v=C1lCQmUSKXw"
phrases["заткнуться"] = "https://www.youtube.com/watch?v=Df7NieM2uqY"
phrases["не понял"] = "https://www.youtube.com/watch?v=j9CQWJ63Fv0"
phrases["не понимаю"] = "https://www.youtube.com/watch?v=j9CQWJ63Fv0"
phrases["убью"] = "https://www.youtube.com/watch?v=xuVYjpk463E"
phrases["понял"] = "https://www.youtube.com/watch?v=kxgCH9u3m9k"
phrases["уничтожить"] = "https://youtu.be/syop7Rsim0s"
phrases["правильно"] = "https://youtu.be/Qk10kFRWrS4"
phrases["позор"] = "https://youtu.be/XwGb4oFXn5Y"
phrases["плохо"] = "https://youtu.be/gspHECRPxdU"
phrases["сидим"] = "https://youtu.be/qI2mKu2qzEA"
phrases["тут"] = "https://youtu.be/qI2mKu2qzEA"
phrases["проход"] = "https://www.youtube.com/watch?v=gU-qZ1JEX_8"
phrases["заход"] = "https://www.youtube.com/watch?v=gU-qZ1JEX_8"
phrases["не получ"] = "https://www.youtube.com/watch?v=6Mv_BDZhY7E"
phrases["мухи"] = "https://www.youtube.com/watch?v=pqyzxHsqzNg"
phrases["выл"] = "https://www.youtube.com/watch?v=I95VY___EwI"
phrases["лекц"] = "https://www.youtube.com/watch?v=YXDeiOXQIC4"
phrases["отжим"] = "https://www.youtube.com/watch?v=S8JzW3dwUp4"
phrases["понравил"] = "https://www.youtube.com/watch?v=O9ilL9oc2w4"
phrases["вкус"] = "https://www.youtube.com/watch?v=qmSYTs17xQQ"
phrases["земля"] = "https://www.youtube.com/watch?v=Ho3lNDC_vLo"
phrases["пизди"] = "https://www.youtube.com/watch?v=g_NwsvkhWQw"
phrases["пирив"] = "https://www.youtube.com/watch?v=4ok4L6DgqP8"
phrases["здарова"] = "https://www.youtube.com/watch?v=4ok4L6DgqP8"
phrases["здравств"] = "https://www.youtube.com/watch?v=4ok4L6DgqP8"
phrases["кулит"] = "https://www.youtube.com/watch?v=4ok4L6DgqP8"
phrases["хороший"] = "https://www.youtube.com/watch?v=W-icECxxclE"
phrases["заебал"] = "https://www.youtube.com/watch?v=vXGEAF_U6Lo"
phrases["поехавший"] = "https://www.youtube.com/watch?v=HLE6-gBpaUA"
phrases["злые"] = "https://www.youtube.com/watch?v=HJZNqDFp6nU"
phrases["нахуя"] = "https://www.youtube.com/watch?v=DIkJgS-Vw-Y"
phrases["есть"] = "https://www.youtube.com/watch?v=qFp7A7PAmz8"
phrases[" мы "] = "https://www.youtube.com/watch?v=cm7YZIlDksY"
phrases["кушать"] = "https://www.youtube.com/watch?v=5wY6SyKBi5U"


